/joy_teleop:
  ros__parameters:
    autonomous_control:
      deadman_buttons:
      - 5
      interface_type: std_msgs/msg/Int8
      message_value:
        data:
          value: 0
      topic_name: /dev/null
      type: topic
    default:
      axis_mappings:
        drive-speed:
          axis: 1
          offset: 0.0
          scale: 0.0
        drive-steering_angle:
          axis: 0
          offset: 0.0
          scale: 0.0
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      type: topic
    human_control:
      axis_mappings:
        drive-speed:
          axis: 1
          offset: 0.0
          scale: 0.8
        drive-steering_angle:
          axis: 3
          offset: 0.0
          scale: 0.34
      deadman_buttons:
      - 4
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      type: topic
    use_sim_time: false
